name: Terraform-Deploy-RG
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
permissions:
  contents: read
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure Azure credentials
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","tenantId":"${{ secrets.TENANT_ID }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}"}'
      - name: Terraform Init
        run: |
          cd RG
          terraform init
      - name: Terraform Plan
        run: |
          cd RG
          terraform plan
      - name: Terraform Apply
        run: |
          cd RG
          terraform apply -auto-approve
